//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital_Sanin_Polupan
{
    using System;
    using System.Collections.Generic;
    
    public partial class Numb1
    {
        public string ФИО_пациентов { get; set; }
        public string Название_услуги { get; set; }
        public string ФИО_сотрудников { get; set; }
        public string PostName { get; set; }
    }
}
