//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital_Sanin_Polupan
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient_sDIagnosis
    {
        public int ID { get; set; }
        public int IDPatient { get; set; }
        public int IDDiagnosis { get; set; }
    
        public virtual Diagnosis Diagnosis { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
